const race = {
  id: 1031,
  year: 2020,
  round: 1,
  name: "Austrian Grand Prix",
  date: "2020-07-05",
  time: "13:10:00",
  url: "http://en.wikipedia.org/wiki/2020_Austrian_Grand_Prix",
  circuit: {
    id: 70,
    ref: "red_bull_ring",
    name: "Red Bull Ring",
    location: "Spielberg",
    country: "Austria",
    lat: 47.2197,
    lng: 14.7647,
    url: "http://en.wikipedia.org/wiki/Red_Bull_Ring",
  },
  qualifying: [
    {
      id: 8735,
      position: 1,
      number: 33,
      q1: "01:30.5",
      q2: "01:30.3",
      q3: "01:29.0",
      race: {
        id: 1052,
        name: "Bahrain Grand Prix",
        year: 2021,
        round: 1,
        date: "2021-03-28",
      },
      driver: {
        id: 830,
        ref: "max_verstappen",
        forename: "Max",
        surname: "Verstappen",
        nationality: "Dutch",
      },
      constructor: {
        id: 9,
        ref: "red_bull",
        name: "Red Bull",
        nationality: "Austrian",
      },
    },
  ],
  results: [
    {
      id: 24665,
      position: 20,
      grid: 10,
      laps: 1,
      points: 0,
      time: "",
      fastestLap: "",
      race: {
        id: 1032,
        year: 2020,
        round: 2,
        name: "Styrian Grand Prix",
        date: "2020-07-12",
      },
      driver: {
        id: 20,
        ref: "vettel",
        forename: "Sebastian",
        surname: "Vettel",
        nationality: "German",
      },
      constructor: {
        id: 6,
        ref: "ferrari",
        name: "Ferrari",
        nationality: "Italian",
      },
    },
  ],
};
const q = [
  {
    id: 8735,
    position: 1,
    number: 33,
    q1: "01:30.5",
    q2: "01:30.3",
    q3: "01:29.0",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 830,
      ref: "max_verstappen",
      forename: "Max",
      surname: "Verstappen",
      nationality: "Dutch",
    },
    constructor: {
      id: 9,
      ref: "red_bull",
      name: "Red Bull",
      nationality: "Austrian",
    },
  },
  {
    id: 8736,
    position: 2,
    number: 44,
    q1: "01:30.6",
    q2: "01:30.1",
    q3: "01:29.4",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 1,
      ref: "hamilton",
      forename: "Lewis",
      surname: "Hamilton",
      nationality: "British",
    },
    constructor: {
      id: 131,
      ref: "mercedes",
      name: "Mercedes",
      nationality: "German",
    },
  },
  {
    id: 8737,
    position: 3,
    number: 77,
    q1: "01:31.2",
    q2: "01:30.2",
    q3: "01:29.6",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 822,
      ref: "bottas",
      forename: "Valtteri",
      surname: "Bottas",
      nationality: "Finnish",
    },
    constructor: {
      id: 131,
      ref: "mercedes",
      name: "Mercedes",
      nationality: "German",
    },
  },
  {
    id: 8738,
    position: 4,
    number: 16,
    q1: "01:30.7",
    q2: "01:30.0",
    q3: "01:29.7",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 844,
      ref: "leclerc",
      forename: "Charles",
      surname: "Leclerc",
      nationality: "Monegasque",
    },
    constructor: {
      id: 6,
      ref: "ferrari",
      name: "Ferrari",
      nationality: "Italian",
    },
  },
  {
    id: 8739,
    position: 5,
    number: 10,
    q1: "01:30.8",
    q2: "01:30.5",
    q3: "01:29.8",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 842,
      ref: "gasly",
      forename: "Pierre",
      surname: "Gasly",
      nationality: "French",
    },
    constructor: {
      id: 213,
      ref: "alphatauri",
      name: "AlphaTauri",
      nationality: "Italian",
    },
  },
  {
    id: 8740,
    position: 6,
    number: 3,
    q1: "01:30.8",
    q2: "01:30.2",
    q3: "01:29.9",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 817,
      ref: "ricciardo",
      forename: "Daniel",
      surname: "Ricciardo",
      nationality: "Australian",
    },
    constructor: {
      id: 1,
      ref: "mclaren",
      name: "McLaren",
      nationality: "British",
    },
  },
  {
    id: 8741,
    position: 7,
    number: 4,
    q1: "01:30.9",
    q2: "01:30.1",
    q3: "01:30.0",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 846,
      ref: "norris",
      forename: "Lando",
      surname: "Norris",
      nationality: "British",
    },
    constructor: {
      id: 1,
      ref: "mclaren",
      name: "McLaren",
      nationality: "British",
    },
  },
  {
    id: 8742,
    position: 8,
    number: 55,
    q1: "01:31.7",
    q2: "01:30.0",
    q3: "01:30.2",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 832,
      ref: "sainz",
      forename: "Carlos",
      surname: "Sainz",
      nationality: "Spanish",
    },
    constructor: {
      id: 6,
      ref: "ferrari",
      name: "Ferrari",
      nationality: "Italian",
    },
  },
  {
    id: 8743,
    position: 9,
    number: 14,
    q1: "01:30.9",
    q2: "01:30.6",
    q3: "01:30.2",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 4,
      ref: "alonso",
      forename: "Fernando",
      surname: "Alonso",
      nationality: "Spanish",
    },
    constructor: {
      id: 214,
      ref: "alpine",
      name: "Alpine F1 Team",
      nationality: "French",
    },
  },
  {
    id: 8744,
    position: 10,
    number: 18,
    q1: "01:31.3",
    q2: "01:30.6",
    q3: "01:30.6",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 840,
      ref: "stroll",
      forename: "Lance",
      surname: "Stroll",
      nationality: "Canadian",
    },
    constructor: {
      id: 117,
      ref: "aston_martin",
      name: "Aston Martin",
      nationality: "British",
    },
  },
  {
    id: 8745,
    position: 11,
    number: 11,
    q1: "01:31.2",
    q2: "01:30.7",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 815,
      ref: "perez",
      forename: "Sergio",
      surname: "PÃ©rez",
      nationality: "Mexican",
    },
    constructor: {
      id: 9,
      ref: "red_bull",
      name: "Red Bull",
      nationality: "Austrian",
    },
  },
  {
    id: 8746,
    position: 12,
    number: 99,
    q1: "01:31.0",
    q2: "01:30.7",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 841,
      ref: "giovinazzi",
      forename: "Antonio",
      surname: "Giovinazzi",
      nationality: "Italian",
    },
    constructor: {
      id: 51,
      ref: "alfa",
      name: "Alfa Romeo",
      nationality: "Swiss",
    },
  },
  {
    id: 8747,
    position: 13,
    number: 22,
    q1: "01:30.6",
    q2: "01:31.2",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 852,
      ref: "tsunoda",
      forename: "Yuki",
      surname: "Tsunoda",
      nationality: "Japanese",
    },
    constructor: {
      id: 213,
      ref: "alphatauri",
      name: "AlphaTauri",
      nationality: "Italian",
    },
  },
  {
    id: 8748,
    position: 14,
    number: 7,
    q1: "01:31.5",
    q2: "01:31.2",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 8,
      ref: "raikkonen",
      forename: "Kimi",
      surname: "RÃ¤ikkÃ¶nen",
      nationality: "Finnish",
    },
    constructor: {
      id: 51,
      ref: "alfa",
      name: "Alfa Romeo",
      nationality: "Swiss",
    },
  },
  {
    id: 8749,
    position: 15,
    number: 63,
    q1: "01:31.3",
    q2: "01:33.4",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 847,
      ref: "russell",
      forename: "George",
      surname: "Russell",
      nationality: "British",
    },
    constructor: {
      id: 3,
      ref: "williams",
      name: "Williams",
      nationality: "British",
    },
  },
  {
    id: 8750,
    position: 16,
    number: 31,
    q1: "01:31.7",
    q2: "",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 839,
      ref: "ocon",
      forename: "Esteban",
      surname: "Ocon",
      nationality: "French",
    },
    constructor: {
      id: 214,
      ref: "alpine",
      name: "Alpine F1 Team",
      nationality: "French",
    },
  },
  {
    id: 8751,
    position: 17,
    number: 6,
    q1: "01:31.9",
    q2: "",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 849,
      ref: "latifi",
      forename: "Nicholas",
      surname: "Latifi",
      nationality: "Canadian",
    },
    constructor: {
      id: 3,
      ref: "williams",
      name: "Williams",
      nationality: "British",
    },
  },
  {
    id: 8752,
    position: 18,
    number: 5,
    q1: "01:32.1",
    q2: "",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 20,
      ref: "vettel",
      forename: "Sebastian",
      surname: "Vettel",
      nationality: "German",
    },
    constructor: {
      id: 117,
      ref: "aston_martin",
      name: "Aston Martin",
      nationality: "British",
    },
  },
  {
    id: 8753,
    position: 19,
    number: 47,
    q1: "01:32.4",
    q2: "",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 854,
      ref: "mick_schumacher",
      forename: "Mick",
      surname: "Schumacher",
      nationality: "German",
    },
    constructor: {
      id: 210,
      ref: "haas",
      name: "Haas F1 Team",
      nationality: "American",
    },
  },
  {
    id: 8754,
    position: 20,
    number: 9,
    q1: "01:33.3",
    q2: "",
    q3: "",
    race: {
      id: 1052,
      name: "Bahrain Grand Prix",
      year: 2021,
      round: 1,
      date: "2021-03-28",
    },
    driver: {
      id: 853,
      ref: "mazepin",
      forename: "Nikita",
      surname: "Mazepin",
      nationality: "Russian",
    },
    constructor: {
      id: 210,
      ref: "haas",
      name: "Haas F1 Team",
      nationality: "American",
    },
  },
];

const r = [
  {
    id: 24646,
    position: 1,
    grid: 1,
    laps: 71,
    points: 25,
    time: "22:50.7",
    fastestLap: 68,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 1,
      ref: "hamilton",
      forename: "Lewis",
      surname: "Hamilton",
      nationality: "British",
    },
    constructor: {
      id: 131,
      ref: "mercedes",
      name: "Mercedes",
      nationality: "German",
    },
  },
  {
    id: 24647,
    position: 2,
    grid: 4,
    laps: 71,
    points: 18,
    time: 13.719,
    fastestLap: 62,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 822,
      ref: "bottas",
      forename: "Valtteri",
      surname: "Bottas",
      nationality: "Finnish",
    },
    constructor: {
      id: 131,
      ref: "mercedes",
      name: "Mercedes",
      nationality: "German",
    },
  },
  {
    id: 24648,
    position: 3,
    grid: 2,
    laps: 71,
    points: 15,
    time: 33.698,
    fastestLap: 70,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 830,
      ref: "max_verstappen",
      forename: "Max",
      surname: "Verstappen",
      nationality: "Dutch",
    },
    constructor: {
      id: 9,
      ref: "red_bull",
      name: "Red Bull",
      nationality: "Austrian",
    },
  },
  {
    id: 24649,
    position: 4,
    grid: 6,
    laps: 71,
    points: 12,
    time: 44.4,
    fastestLap: 67,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 848,
      ref: "albon",
      forename: "Alexander",
      surname: "Albon",
      nationality: "Thai",
    },
    constructor: {
      id: 9,
      ref: "red_bull",
      name: "Red Bull",
      nationality: "Austrian",
    },
  },
  {
    id: 24650,
    position: 5,
    grid: 9,
    laps: 71,
    points: 10,
    time: "+1:01.470",
    fastestLap: 66,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 846,
      ref: "norris",
      forename: "Lando",
      surname: "Norris",
      nationality: "British",
    },
    constructor: {
      id: 1,
      ref: "mclaren",
      name: "McLaren",
      nationality: "British",
    },
  },
  {
    id: 24651,
    position: 6,
    grid: 17,
    laps: 71,
    points: 8,
    time: "+1:02.387",
    fastestLap: 68,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 815,
      ref: "perez",
      forename: "Sergio",
      surname: "PÃ©rez",
      nationality: "Mexican",
    },
    constructor: {
      id: 211,
      ref: "racing_point",
      name: "Racing Point",
      nationality: "British",
    },
  },
  {
    id: 24652,
    position: 7,
    grid: 12,
    laps: 71,
    points: 6,
    time: "+1:02.453",
    fastestLap: 65,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 840,
      ref: "stroll",
      forename: "Lance",
      surname: "Stroll",
      nationality: "Canadian",
    },
    constructor: {
      id: 211,
      ref: "racing_point",
      name: "Racing Point",
      nationality: "British",
    },
  },
  {
    id: 24653,
    position: 8,
    grid: 8,
    laps: 71,
    points: 4,
    time: "+1:02.591",
    fastestLap: 65,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 817,
      ref: "ricciardo",
      forename: "Daniel",
      surname: "Ricciardo",
      nationality: "Australian",
    },
    constructor: {
      id: 4,
      ref: "renault",
      name: "Renault",
      nationality: "French",
    },
  },
  {
    id: 24654,
    position: 9,
    grid: 3,
    laps: 70,
    points: 3,
    time: "",
    fastestLap: 68,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 832,
      ref: "sainz",
      forename: "Carlos",
      surname: "Sainz",
      nationality: "Spanish",
    },
    constructor: {
      id: 1,
      ref: "mclaren",
      name: "McLaren",
      nationality: "British",
    },
  },
  {
    id: 24655,
    position: 10,
    grid: 13,
    laps: 70,
    points: 1,
    time: "",
    fastestLap: 60,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 826,
      ref: "kvyat",
      forename: "Daniil",
      surname: "Kvyat",
      nationality: "Russian",
    },
    constructor: {
      id: 213,
      ref: "alphatauri",
      name: "AlphaTauri",
      nationality: "Italian",
    },
  },
  {
    id: 24656,
    position: 11,
    grid: 16,
    laps: 70,
    points: 0,
    time: "",
    fastestLap: 57,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 8,
      ref: "raikkonen",
      forename: "Kimi",
      surname: "RÃ¤ikkÃ¶nen",
      nationality: "Finnish",
    },
    constructor: {
      id: 51,
      ref: "alfa",
      name: "Alfa Romeo",
      nationality: "Swiss",
    },
  },
  {
    id: 24657,
    position: 12,
    grid: 15,
    laps: 70,
    points: 0,
    time: "",
    fastestLap: 69,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 825,
      ref: "kevin_magnussen",
      forename: "Kevin",
      surname: "Magnussen",
      nationality: "Danish",
    },
    constructor: {
      id: 210,
      ref: "haas",
      name: "Haas F1 Team",
      nationality: "American",
    },
  },
  {
    id: 24658,
    position: 13,
    grid: 0,
    laps: 70,
    points: 0,
    time: "",
    fastestLap: 69,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 154,
      ref: "grosjean",
      forename: "Romain",
      surname: "Grosjean",
      nationality: "French",
    },
    constructor: {
      id: 210,
      ref: "haas",
      name: "Haas F1 Team",
      nationality: "American",
    },
  },
  {
    id: 24659,
    position: 14,
    grid: 19,
    laps: 70,
    points: 0,
    time: "",
    fastestLap: 54,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 841,
      ref: "giovinazzi",
      forename: "Antonio",
      surname: "Giovinazzi",
      nationality: "Italian",
    },
    constructor: {
      id: 51,
      ref: "alfa",
      name: "Alfa Romeo",
      nationality: "Swiss",
    },
  },
  {
    id: 24660,
    position: 15,
    grid: 7,
    laps: 70,
    points: 0,
    time: "",
    fastestLap: 69,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 842,
      ref: "gasly",
      forename: "Pierre",
      surname: "Gasly",
      nationality: "French",
    },
    constructor: {
      id: 213,
      ref: "alphatauri",
      name: "AlphaTauri",
      nationality: "Italian",
    },
  },
  {
    id: 24661,
    position: 16,
    grid: 11,
    laps: 69,
    points: 0,
    time: "",
    fastestLap: 36,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 847,
      ref: "russell",
      forename: "George",
      surname: "Russell",
      nationality: "British",
    },
    constructor: {
      id: 3,
      ref: "williams",
      name: "Williams",
      nationality: "British",
    },
  },
  {
    id: 24662,
    position: 17,
    grid: 18,
    laps: 69,
    points: 0,
    time: "",
    fastestLap: 68,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 849,
      ref: "latifi",
      forename: "Nicholas",
      surname: "Latifi",
      nationality: "Canadian",
    },
    constructor: {
      id: 3,
      ref: "williams",
      name: "Williams",
      nationality: "British",
    },
  },
  {
    id: 24663,
    position: 18,
    grid: 5,
    laps: 25,
    points: 0,
    time: "",
    fastestLap: 22,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 839,
      ref: "ocon",
      forename: "Esteban",
      surname: "Ocon",
      nationality: "French",
    },
    constructor: {
      id: 4,
      ref: "renault",
      name: "Renault",
      nationality: "French",
    },
  },
  {
    id: 24664,
    position: 19,
    grid: 14,
    laps: 4,
    points: 0,
    time: "",
    fastestLap: 3,
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 844,
      ref: "leclerc",
      forename: "Charles",
      surname: "Leclerc",
      nationality: "Monegasque",
    },
    constructor: {
      id: 6,
      ref: "ferrari",
      name: "Ferrari",
      nationality: "Italian",
    },
  },
  {
    id: 24665,
    position: 20,
    grid: 10,
    laps: 1,
    points: 0,
    time: "",
    fastestLap: "",
    race: {
      id: 1032,
      year: 2020,
      round: 2,
      name: "Styrian Grand Prix",
      date: "2020-07-12",
    },
    driver: {
      id: 20,
      ref: "vettel",
      forename: "Sebastian",
      surname: "Vettel",
      nationality: "German",
    },
    constructor: {
      id: 6,
      ref: "ferrari",
      name: "Ferrari",
      nationality: "Italian",
    },
  },
];
